### PR TITLE
Update main from dev #3

### PR DESCRIPTION
**Pull request by aaronreed708**
Update main from dev to get benefit of dependency updates, documentation updates and new enhancements.

### CODE REVIEW

**Comment by aaronreed708** [comment]
@TheJuanAndOnly99 emailed me and said that there is currently an error with the GitHub API that is reporting an EasyCLA error even though Kris fixed her email issues.  He said that the CLA signature has been verified.  Asking for reviews and then this PR should be good to merge.

**Comment by PaulaPaul** [comment]
Given the EasyCLA issue is resolved (or expected) I'm in favor of this merge - it's quite large but I think the risk of merge issues should be easy to 'fail forward' on-

**Review by PaulaPaul — APPROVED** [review]
Thanks @aaronreed708  - adding my approval here and happy to help with any post merge issues given the size of this batch.
Cheers!

**Review by lwnoble — APPROVED** [review]
Happy to review Aaron - looks good.

**Review by smithbk — APPROVED** [review]
LGTM Aaron

**Comment by aaronreed708** [comment]
Because this was ok'd by @TheJuanAndOnly99, merging.

**Pull request merged**
