### PR TITLE
Update Linter Changes as discussed in #875

### LINKED ISSUE #897: Add Linter Changes to Our Codebase
I think that this code looks just fine.  I'll merge it.  @Sweetdevil144 can you open an issue that can be used to create the PR to commit the updated/fixed code, please?

_Originally posted by @aaronreed708 in https://github.com/finos/a11y-theme-builder/pull/875#pullrequestreview-2070063680_

### PR DESCRIPTION
**Pull request by Sweetdevil144**
Fixes #897 

This PR introduces Linter changes to our Repository

### CODE REVIEW

**Comment by Sweetdevil144** [comment]
Hmmm. I Just noticed that our Linter Changes **DO NOT** remove unused variables even though we've utilized importing.

Would our script need further debugging and changes?

Tagging @aaronreed708 for further views.

**Comment by Sweetdevil144** [comment]
All Linting changes applied

**Comment by aaronreed708** [comment]
> 
> Tagging @aaronreed708 for further views.

I did some quick googling.  It looks like linter can fix unused imports automatically, but I didn't see anything about it fixing unused variables.  Just warns about them.

**Comment by Sweetdevil144** [comment]
Header rules are failing. I'll rectify the issue as soon as possible. I'm looking more into the issue. Sorry for the delay due to lack of time.

**Comment by Sweetdevil144** [comment]
Closing this PR. Will Open a new soon

**Comment by Sweetdevil144** [comment]
> I did some quick googling. It looks like linter can fix unused imports automatically, but I didn't see anything about it fixing unused variables. Just warns about them.

Should we take alook in this package ? Looks like this componsates for removing unused variables :
https://www.npmjs.com/package/@putout/plugin-remove-unused-variables

**Pull request closed without merging**
