### PR TITLE
fix #856 : Linter added for Code Cleanup

### LINKED ISSUE #856: [REQUEST] Code Cleanup: Remove Unused Imports and Variables
### Suggestion/Concern
There are unused imports in some of the code files. For example, in one of the files, the hooks `useRef` and `useLayoutEffect` are imported from 'react' but are not used anywhere in the file `code/src/ui/src/pages/DesignSystemPage.tsx`. This is unnecessary and can lead to confusion.

### Proposed Solution
Perform a thorough review of the codebase to identify any unused imports, variables, or other code elements. Once identified, these should be removed to keep the codebase clean and efficient. This will also help in improving the readability of the code and reduce the complexity. We can also add linter features to the same and implement **linting before testing** to keep track of such future issues.

Although I realise that MAYBE these will be utilised in near future, maintaining code quality is also an aspect we'll need to look over.

```typescript
// For example, in the file `code/src/ui/src/pages/DesignSystemPage.tsx` we have:
import React, { useRef, useLayoutEffect, ReactNode } from 'react';

// But useRef and useLayoutEffect are not used anywhere in the file.
// So, the import statement should be cleaned up to:
import React, { ReactNode } from 'react';
```

### PR DESCRIPTION
**Pull request by Sweetdevil144**
Fixes #856 

Linter Added to base location to detect Linting Issues.

### CODE REVIEW

**Review by aaronreed708 — COMMENTED** [review]
I'm seeing errors like this at the top of the output that is generated by `npm run lint`:

```
/Users/aaron/git-finos/a11y-theme-builder/code/build/app.js
  0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/build/app.js` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json
However, that TSConfig does not include this file. Either:
- Change ESLint's list of included files to not include this file
- Change that TSConfig to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
```

Do you see them, too?  Can they be resolved?

**Comment by Sweetdevil144** [comment]
> Do you see them, too? Can they be resolved?

My bad. I forgot to add the `ignorePatterns` Property. This error may be fixed now. Can you verify it @aaronreed708 ?

**Comment by Sweetdevil144** [comment]
As an addition to Linting, maybe we can also ad `Prettier` Formatting to this PR if you agree to do so @aaronreed708

**Comment by aaronreed708** [comment]
#876  is already underway for Prettier with a PR.  No reason that we can't keep them separate.

**Comment by aaronreed708** [comment]
> My bad. I forgot to add the `ignorePatterns` Property. This error may be fixed now. Can you verify it @aaronreed708 ?

That fixed the parsing error, thank you!

**Review by aaronreed708 — APPROVED** [review]
I think that this code looks just fine.  I'll merge it.  @Sweetdevil144 can you open an issue that can be used to create the PR to commit the updated/fixed code, please?

**Comment by Sweetdevil144** [comment]
Sure. Shiting the convo to #897

**Pull request merged**
