### PR TITLE
Update Linter changes

### LINKED ISSUE #897: Add Linter Changes to Our Codebase
I think that this code looks just fine.  I'll merge it.  @Sweetdevil144 can you open an issue that can be used to create the PR to commit the updated/fixed code, please?

_Originally posted by @aaronreed708 in https://github.com/finos/a11y-theme-builder/pull/875#pullrequestreview-2070063680_

### PR DESCRIPTION
**Pull request by Sweetdevil144**
Fixes #897 

This PR introduces Linter changes as discussed with @aaronreed708 in #897

### CODE REVIEW

**Comment by Sweetdevil144** [comment]
Should we take alook in this package ? Looks like this componsates for removing unused variables :
https://www.npmjs.com/package/@putout/plugin-remove-unused-variables

Idon't understand why header rules are failing ven when We ignore headers

**Comment by Sweetdevil144** [comment]
Following are major Error Warnings we are getting :

- Unused variables and imports
- `any` type in TypeScript
- Duplicate imports

Does anyone else have any idea to fix it?

**Comment by aaronreed708** [comment]
> Does anyone else have any idea to fix it?
I'm guessing that we may have to do it manually other than maybe duplicate imports

**Comment by Sweetdevil144** [comment]
> > Does anyone else have any idea to fix it?
> > I'm guessing that we may have to do it manually other than maybe duplicate imports

@aaronreed708 there are 778 instances of such error. Can you checkout the above extension I mentioned? Manually would take too uch time and effort in waste.

**Comment by aaronreed708** [comment]
I guess that it is worth a shot.  Have you tried it, yet?

**Pull request closed without merging**
