### PR TITLE
fix: removed some stashed changed git output

### PR DESCRIPTION
**Pull request by toni-sharpe**
* accidentally commited stashed chnage merge issue, I just removed the git merge error output bit, not sure how this affects anything but thought I'd just get it open and visible for that

### CODE REVIEW

**Review by aaronreed708 — COMMENTED** [review]
Hi @toni-sharpe, patch looks good, that you for the contribution!. But could you please make it against the dev branch, please?  That is where all commits should be made.  Thanks!

Also, have you submitted for CLA approval?  I can't merge anyone until that is taken care of.

**Comment by toni-sharpe** [comment]
@aaronreed708 further to your Slack message I would appreciate it if you just did it and closed this. I thought it would be an easy one because it's simply removing accidental commit noise. At this point I have a few things going on, so taking that off my hands would be appreciated.

**Comment by aaronreed708** [comment]
Per @toni-sharpe I addressed this in https://github.com/finos/a11y-theme-builder/pull/998 which has been merged.  So closing this PR.

**Comment by toni-sharpe** [comment]
Thanks for resolving this :-)

**Pull request closed without merging**
