### PR TITLE
#368: Docs updated. 'People with disabilities' replaced with 'people needing accommodations'

### PR DESCRIPTION
**Pull request by kris-reed**
'People with disabilities' replaced with 'people needing accommodations'. A second revision was required as 3 instances of "people needing accommodations and disorders" was noted after initial update.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Nice ! looks much more polite than the previous one .

**Review by aaronreed708 — COMMENTED** [review]
I like all of these changes, thank you for making them!  However, I'd like this PR to also address the documentation that brought about the issue #368.  Finding an alternative to "Impaired Person" and changing the appropriate places in the documentation.

Also, please re-submit this PR based off of the `dev` branch and not `main`.  Thank you!

**Comment by kris-reed** [comment]
@aaronreed708 I'll have to attend to it over the weekend. Thanks for the input! 

As for an alternative to "impaired person," is "person needing accommodations" overkill on that phrasing?

**Comment by aaronreed708** [comment]
> As for an alternative to "impaired person," is "person needing accommodations" overkill on that phrasing?

I see 3 places where "Impaired Person" is used.  In those 3 places, I think "Person Needing Accommodations" will work fine, but I think you should see for yourself if you end up feeling the same as I do.  "Person Needing Accommodations" is a pretty heavy phrase (long, lots of syllables), but I can't think of a better way to say it.

**Comment by kris-reed** [comment]
@aaronreed708 I had the same thoughts on the matter. If it's only 3 mentions, my next thought would be how close they are in proximity. I'm going to take stock of this when I look it over early this week.

**Comment by aaronreed708** [comment]
closing this PR as this work was accomplished by https://github.com/finos/a11y-theme-builder/pull/861

**Pull request closed without merging**
