### PR TITLE
Update CONTRIBUTE.md

### PR DESCRIPTION
**Pull request by PaulaPaul**
adding details about the regular community call, and participating in conferences and meetups.

### CODE REVIEW

**Comment by aaronreed708** [comment]
@PaulaPaul can you create another PR to merge this to the dev branch first?  Then we can move it to main branch.  Thanks!

**Comment by PaulaPaul** [comment]
> @PaulaPaul can you create another PR to merge this to the dev branch first? Then we can move it to main branch. Thanks!

Ah, apologies for that @aaronreed708 will do

**Comment by PaulaPaul** [comment]
> > @PaulaPaul can you create another PR to merge this to the dev branch first? Then we can move it to main branch. Thanks!
> 
> Ah, apologies for that @aaronreed708 will do

Hi @aaronreed708 - the PR to merge to dev has been completed - let me know if you need action on my part to merge to main, or if that comes directly from dev I can close this PR. Thanks!

**Comment by aaronreed708** [comment]
If you want to get it into main right away, we can do that, I just need to get another contributor to review it, too.  If it can wait until the next release, then it would move into main along with all of the other stuff on the dev branch.

**Comment by PaulaPaul** [comment]
Closing this PR (which is targeted at a direct merge to main) - this change has been merged to dev and will be merged to main on the next update from dev. Thanks @aaronreed708 -

**Pull request closed without merging**
